#! /bin/sh

# Remove existing rules to avoid duplication
bspc rule -r '*'

# Set cursor appearance
xsetroot -cursor_name left_ptr

# Start hotkey daemon
sxhkd &

# Start panel bar
polybar main &

# bspwm config
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
