return {
    lsp = {
        "bashls",
        "cssls",
        "dockerls",
        "eslint",
        "golangci_lint_ls",
        "gopls",
        "graphql",
        "jsonls",
        "pyright",
        "rust_analyzer",
        "lua_ls",
        "svelte",
        "terraformls",
        "tsserver",
        "yamlls",
    },
    linter = {
        "flake8",
        "hadolint",
    },
    formatter = {
        "black",
        "goimports",
        "prettierd",
        "shfmt",
        "stylua",
    },
    dap = {
        "delve",
        "node-debug2",
        "python",
    },
}
