vim.opt.clipboard = 'unnamedplus' -- Use system clipboard
vim.opt.ignorecase = true -- Ignore case
vim.opt.inccommand = 'split' -- Preview for find-replace command
vim.opt.number = true -- Show line numbers
vim.opt.relativenumber = true -- Relative line numbers
vim.opt.shortmess = 'I' -- Disable welcome screen
vim.opt.smartcase = true -- Do not ignore case with capitals
vim.opt.spelllang = 'en_us' -- Command-line completion mode
vim.opt.splitbelow = true -- Put new windows below current
vim.opt.splitright = true -- Put new windows right of current
vim.opt.termguicolors = true -- True color support
